seed: 1
batch_size: 8192
num_iters: 10000
pretrain_iters: 1000
tau: 0.99
num_actions: 2
pretrain_vs_random: True
supervised_pretrain: False
do_self_play: True
use_ipd_g_param: True
ipd_g: 1.3
shift_d: 0
shift_c: -1
wandb_dir: /scratch/
agent:
  num_actions: 2
  in_size: 4
  out_size: 2
  hidden_size: 32
  capacity: 1000000
  gamma: 0.8
  epsilon: 0.1
  decay_eps: True
  eps_start: 0.5
  eps_end: 0.005
  eps_decay: 1000
  optim_type: "sgd"
  loss_type: "huber"
optim:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0
  beta_1: 0.9
  beta_2: 0.999
